### PR TITLE
Add support for exec command in rebase mode

### PR DESCRIPTION
**Pull request by 50Wliu**
This is a continuation of #21, with specs.

Closes #21.

Thanks very much @astorije for your initial work on this!

### CODE REVIEW

**Comment by 50Wliu** [comment]
`appveyor/branch` is superfluous and has already been removed in cf108be9bf2d5dabc36ba1ba8dcf9a2e9722b0fe.

**Comment by astorije** [comment]
Thanks for taking this over, @50Wliu, and sorry I didn't do that myself!
I'll take a look at your awesome work :-)

**Comment by astorije** [comment]
Het @50Wliu, just wondering, do you know when this is supposed to reach the public release channel?
No pressure of course, I am just trying to assess timeline as I'm going to demo something involving `exec` and I will project Atom along with it :-)

**Comment by 50Wliu** [comment]
I'm on vacation right now and can't easily check, but from memory I'm pretty sure this will be available starting in Atom 1.10.0.

**Pull request merged**
